name: relayer-contracts
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "npm"
      - run: npm i
      - run: npx prettier --check .
      - run: npx eslint .
      - run: npx hardhat test
      - name: Test deployment script
        run: npx hardhat run scripts/deploy.ts
