name: relayer-contracts
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 22
      - uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm i
      # - run: npx prettier --check .
      # - run: npx eslint .
      - run: npx hardhat test
      - name: Test deployment script
        run: npx hardhat run scripts/deploy.ts
